# Site settings
title: Dr. Steve Kelman - Government Procurement Consulting
email: steve_kelman@hks.harvard.edu
description: >-
  Consulting services for progressive procurement
  executives and leaders in the public sector.
keywords: federal, government, procurement, acquisition, executive, consulting
baseurl: ""
url: https://stevekelman.com
localhost: localhost:4000
twitter_username: @KelmanSteve

# Build settings
markdown: kramdown

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
